version: "3.9"
services:
  zoo_app:
    build: "./zoo"
    ports:
      - "3000:3000"
    links:
      - pg_db
  user_app:
    build: "./users"
    ports:
      - "5000:5000"
    links:
      - pg_db
  react_app:
    build: "./front/"
    ports:
      - "3001:3001"
    depends_on:
      - zoo_app
      - user_app
    links:
      - zoo_app
      - user_app
  pg_db:
    image: postgres
    ports:
      - "${DB_LOCAL_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "3002:80"
    depends_on:
      - react_app
      - zoo_app
      - user_app

volumes:
  pg_data:
