apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo
spec:
  selector:
    matchLabels:
      app: zoo
  replicas: 1
  template:
    metadata:
      labels:
        app: zoo
    spec:
      containers:
        - name: zoo
          image: h4rasho/zoo:latest
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASS
              value: "gdk1JlTM"
            - name: DB_NAME
              value: "zoo"
            - name: DB_DIALECT
              value: "postgres"
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: zoo
spec:
  type: NodePort
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30000
  selector:
    role: zoo